### ISSUE TITLE
Datenbank

### ISSUE THREAD

**Issue by saiz97** [htl-leonding/2016_Tessa#3]
End-Termin: 04-06-2016

Vorzeige-Db der Rezepte soll fertig befüllt werden

**Comment by FurtakS** [comment]
Abgeschlossen: 02-06-2016 (vergessen den Issue zu schließen, abgesprochen mit Projektleiter)

**Comment by saiz97** [comment]
Rezept-Datenbank soll für die Suche, wie abgesprochen erweitert werden!
Beispiel: Pina Colada - Cocktail

**Comment by saiz97** [comment]
mehr Daten/Rezepte in die Rezeptdatenbank! :fork_and_knife: :squirrel:
