### ISSUE TITLE
Erstellen der Produktliste

### ISSUE THREAD

**Issue by saiz97** [htl-leonding/2016_Tessa#4]
End-Termin: 08-06-2016

Erstellt werden soll eine Liste mit Produkten, welche keinen Barcode besitzen.
Beispiel: Fisch, Obst, Fleisch, etc.

Absprache mit Team am Wochenende 04/05-06-2016

**Comment by FurtakS** [comment]
Vorläufige Liste erstellt (min. 5 Produkte pro Kategorie, 7 Kategorien)
