### ISSUE TITLE
Rezeptansicht

### ISSUE THREAD

**Issue by saiz97** [htl-leonding/2016_Tessa#5]
End-Termin: 12-08-2016

Rezeptansicht überarbeiten
Rezeptdaten aus der Datenbank kontrollieren und passend darstellen

**Comment by saiz97** [comment]
Zur Anzeige eines Rezepts soll statt dem PopUp ein Popout verwendet werden
[Popout](http://materializecss.com/collapsible.html)

**Comment by korti11** [comment]
Slider mit zufälligen Rezepten von da Rezeptseite auf die Hauptseite verlegen.

**Comment by saiz97** [comment]
Hinzuzufügen - Favorit-Funktion #6 
Soweit ist dieser issue abgearbeitet, deshalb ~closed
